### ISSUE TITLE
[Question to the author] How to relax (shorten) Shell_TrayWnd vertical min width

### ISSUE THREAD

**Issue by nanoant** [m417z/taskbar-resize#1]
Hi @RaMMicHaeL,
I have figured out that you are the author of [7+ Taskbar Tweaker](https://rammichael.com/7-taskbar-tweaker). I don't want to create by no means any competing product. Instead I want to create simple some open source solution for own needs that relaxes (makes smaller) vertical taskbar width on Windows 10, which is simple too big and drives me crazy.

I know that 7+ Taskbar Tweaker lets you do that, but I cannot run 3rd party software using injection on my workstation. But I can run software I compile myself 🤗

I have forked https://github.com/rikka0w0/Taskbar-Context-Menu-Tweaker and tried to override `WM_SIZING` and/or `WM_SIZE` but if I skip calling original taskbar window proc I cannot resize it at all. So I essentially have all I need, but the final recipe.

I was playing around with different solutions, and so far only this hack working https://github.com/nanoant/Taskbar-Context-Menu-Tweaker/commit/b2caa2d77bddbb5fe2fa307cf4a55a0e987954fc

This is far far from perfect, as I just want to stop taskbar preventing me from shrinking it.

So, now the question to you, would you mind sharing how you achieved `no_width_limit=1` as described by you here:
* https://rammichael.com/7-taskbar-tweaker#comment-10025
* https://superuser.com/questions/1057518/windows-10-taskbar-how-to-make-it-thinner-when-vertical/1057576#1057576

**Comment by m417z** [comment]
Hi @nanoant,

The `no_width_limit` option has two different implementations, one for Windows 7 and one for Windows 8 and 10. For Windows 7, I handle `WM_SIZING` and set an internal flag which bypasses the minimal width check. For Windows 8 and 10, the trick I use is hooking `MulDiv` and returning a small number for `nNumber == 62 && nDenominator == 96`. Not very elegant, but works surprisingly well.

**Comment by nanoant** [comment]
@RaMMicHaeL Wow, thanks for the explanation of `MulDiv` trick. It would take me ages to get there 😄 I will definitely try that tomorrow.

**Comment by nanoant** [comment]
@RaMMicHaeL Well I tried `MulDiv` hook, but it did not work for me. Indeed I was observing `nNumber == 62 && nDenominator == 120` (NOTE: `120` instead `96` - I suppose because I use 125% DPI scaling) and I was returning something like `20` but this did not let task-bar to be shrunk more.

However I found another way to fool vertical task-bar min width check.
When my task-bar is on the left side and I receive `WM_SIZING` with right edge, I simply make `lpRect->left -= 30` (makes left `-30` instead of `0`) before passing message to original window proc. This fools the width calculation so I have 30 extra pixels to shrink the task-bar, but does not run the layout and has no side-effects (at least none observed so far).

**Comment by m417z** [comment]
> `120` instead `96`

The parameter that should be changing due to DPI is `nNumerator`.

> I was returning something like `20` but this did not let task-bar to be shrunk more.

That's strange, since it works for the tweaker since Windows 8. I re-checked, and it still works, so perhaps you were doing something wrong.

> However I found another way to fool vertical task-bar min width check.

Interesting, I haven't thought of or tried doing this. I'll keep this in mind in case my method will break someday in the future.

**Comment by garyng** [comment]
Hi! I tried hooking into `MulDiv` but find no calls with `nNumber == 62`... Does it change recently?
![image](https://user-images.githubusercontent.com/4453664/96414102-3bb5fa00-121f-11eb-94d2-d7e485b225fe.png)


_Note: I can't use the Tweaker tool because it's a workstation..._ 😢

**Comment by garyng** [comment]
I tried hooking calls to `MulDiv` but couldn't capture any. Turns out on Windows 10 you need to hook `MulDiv` inside `api-ms-win-core-largeinteger-l1-1-0.dll` instead of `User32.dll`
