### ISSUE TITLE
Not work on Windows 10

### ISSUE THREAD

**Issue by ixvz** [m417z/taskbar-resize#2]
command 

taskbar_resize.exe -l 32

not effect (:

**Comment by m417z** [comment]
1. Is the taskbar unlocked?
2. Did you try it with larger numbers, such as 100 or 150?

It would be nice if unlocking wouldn't be required, but it's just a tiny tool somebody asked me to create back then and it was good enough.

**Comment by ixvz** [comment]
> 1. Is the taskbar unlocked?
> 2. Did you try it with larger numbers, such as 100 or 150?
> 
> It would be nice if unlocking wouldn't be required, but it's just a tiny tool somebody asked me to create back then and it was good enough.

yes indeed 62+ works great

I thought with this tool you can reduce the width of the vertical panel to 32px :)

**Comment by m417z** [comment]
> I thought with this tool you can reduce the width of the vertical panel to 32px :)

Nope, but as you might already know, you can use [7+ Taskbar Tweaker](https://tweaker.ramensoftware.com/) for that.

**Comment by ixvz** [comment]
> > I thought with this tool you can reduce the width of the vertical panel to 32px :)
> 
> Nope, but as you might already know, you can use [7+ Taskbar Tweaker](https://tweaker.ramensoftware.com/) for that.

Thanks for the answer

Yes of course I know about 7+ Taskbar
but after launching it, the taskbar starts to twitch - like when restarting explorer.exe
I only need a narrow panel)

**Comment by m417z** [comment]
> but after launching it, the taskbar starts to twitch - like when restarting explorer.exe

Maybe we can figure that out. Can you capture a crash dump with `ProcDump`? Run `procdump64.exe -mp -e explorer.exe` and trigger the crash. The dump will be written to a file, the details will be printed in the ProcDump console window.

> I only need a narrow panel)

If you're up to a programming experience, you can see the (mostly full) implementation here:

A hook to overcome the limitation:
https://github.com/m417z/7-Taskbar-Tweaker/blob/6c456b7b0da8025bbfb37551cee2c9f4782ae4ae/dll/wnd_proc.c#L4438-L4444

The programmatic resizing:
https://github.com/m417z/7-Taskbar-Tweaker/blob/6c456b7b0da8025bbfb37551cee2c9f4782ae4ae/dll/wnd_proc.c#L1189-L1208

**Comment by ixvz** [comment]
Thank you
I'm not good at programming :(
file
https://files.catbox.moe/weuk9n.dmp

was created the moment the panel blinked https://imgur.com/a/eqtFkXy

**Comment by m417z** [comment]
Looks like you're using Windows Server 2022, not Windows 10. It wasn't supported. This is the first Windows Server version which has a unique build number (20348), not shared by any non-Server Windows version:
https://en.wikipedia.org/wiki/Windows_NT#Releases

I tried to add support to it. Please try [the latest beta version](https://ramensoftware.com/7-taskbar-tweaker#download), let me know whether it works.

**Comment by ixvz** [comment]
> Looks like you're using Windows Server 2022, not Windows 10. It wasn't supported. This is the first Windows Server version which has a unique build number (20348), not shared by any non-Server Windows version: https://en.wikipedia.org/wiki/Windows_NT#Releases
> 
> I tried to add support to it. Please try [the latest beta version](https://ramensoftware.com/7-taskbar-tweaker#download), let me know whether it works.

https://ramensoftware.com/downloads/7tt_setup_beta.exe

the panel also restarts ):

**Comment by ixvz** [comment]
i run 7+ Taskbar Tweaker
the panel becomes the desired width
then close 7Taskbar
and panel settings are saved :)
it's a bit wrong - but it works)

**Comment by m417z** [comment]
> the panel also restarts ):

What do you mean? That explorer crashes?

> it's a bit wrong

What's wrong? Did you expect it to return to the previous width when you close the tweaker?

> but it works)

Great. So I guess it doesn't crash? :)

**Comment by ixvz** [comment]
> 7+ Taskbar

When starting 7+ Taskbar - explorer sometimes starts restarting
the width of the panel remains as it is configured by 7+ Taskbar - if I exit it :)
I can't explain better - my English is bad)

**Comment by m417z** [comment]
> When starting 7+ Taskbar - explorer sometimes starts restarting

Can you capture and upload the dump with ProcDump?

> the width of the panel remains as it is configured by 7+ Taskbar - if I exit it :)

Yes, that's how it works. I see no reason to prefer some other behavior :)

**Comment by m417z** [comment]
I believe that I found and fixed the crash. Please try the new beta version, 5.12.3.4.

**Comment by ixvz** [comment]
> I believe that I found and fixed the crash. Please try the new beta version, 5.12.3.4.

Sorry for the long break!!
yes in version 5.12.3.4 I was unable to cause a crash! Everything works, thank you!!!

**Comment by m417z** [comment]
Great. I'm closing the issue since this project wasn't designed for this.
