### ISSUE TITLE
how to resize the bottom taskbar ?

### ISSUE THREAD

**Issue by badrelmers** [m417z/taskbar-resize#3]
Hi,
please is it possible to resize the taskbar when it is in bottom or top position? is it even possible with the win api? i m using win 7
thank you

**Comment by m417z** [comment]
It's an old project. I don't think I tried that, but you can try modifying the code in this repo to change the height instead of the width, perhaps it will work.
Nowadays I use Windows 11, which has a new taskbar implementation. For Windows 11, there's the [Taskbar height and icon size](https://windhawk.net/mods/taskbar-icon-size) Windhawk mod.

**Comment by badrelmers** [comment]
thank you for your answer,  I will update this thread with the solution if i m able to solve it

**Comment by badrelmers** [comment]
it worked like you told me :) it was making me crazy because nothing wanted to work before finding your code, here is the code:

```C
// no need to compile 64, compile only 32 version it works fine with win7 64 

#include <windows.h>
#include <shlwapi.h>

void main()
{
    int argc;
    WCHAR **argv = CommandLineToArgvW(GetCommandLine(), &argc);

    if(argv)
    {
        if(argc >= 3)
        {
            BOOL bBottom = lstrcmpi(argv[1], L"-b") == 0;
            BOOL bTop = lstrcmpi(argv[1], L"-t") == 0;
            BOOL bRight = lstrcmpi(argv[1], L"-r") == 0;
            BOOL bLeft = lstrcmpi(argv[1], L"-l") == 0;
            int nMySize = StrToInt(argv[2]);

            HWND hTaskbarWnd = FindWindow(L"Shell_TrayWnd", NULL);
            if(hTaskbarWnd)
            {
                RECT rc;
                GetWindowRect(hTaskbarWnd, &rc);

                if(bBottom) {
                    rc.top = rc.bottom - nMySize;
                    SendMessage(hTaskbarWnd, WM_SIZING, WMSZ_TOP, (LPARAM)&rc);
                    SetWindowPos(hTaskbarWnd, NULL, 0, 0, rc.right - rc.left, nMySize, SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE);
                }
                else if(bTop) {
                    rc.bottom = rc.top + nMySize;
                    SendMessage(hTaskbarWnd, WM_SIZING, WMSZ_BOTTOM, (LPARAM)&rc);
                    SetWindowPos(hTaskbarWnd, NULL, 0, 0, rc.right - rc.left, nMySize, SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE);
                }
                else if(bRight) {
                    rc.left = rc.right - nMySize;
                    SendMessage(hTaskbarWnd, WM_SIZING, WMSZ_LEFT, (LPARAM)&rc);
                    SetWindowPos(hTaskbarWnd, NULL, 0, 0, nMySize, rc.bottom - rc.top, SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE);
                }
                else if(bLeft) {
                    rc.right = rc.left + nMySize;
                    SendMessage(hTaskbarWnd, WM_SIZING, WMSZ_LEFT, (LPARAM)&rc);
                    SetWindowPos(hTaskbarWnd, NULL, 0, 0, nMySize, rc.bottom - rc.top, SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE);
                }
            }
        }

        LocalFree(argv);
    }

    ExitProcess(0);
}
```

it seems that buffer.h is  not used so I removed it.

NB: for top and bottom positions, you cannot resize to 3 rows from 1 row you have to resize to 2 rows first then resize to 3 rows

the following numbers are based on the taskbar with small icons not the big ones

```batch
taskbar_resize.exe -b 60 ===> 1 row
taskbar_resize.exe -b 70 ===> 2 rows
taskbar_resize.exe -b 110 ===> 3 rows
taskbar_resize.exe -b 150 ===> 4 rows
taskbar_resize.exe -b 180 ===> 5 rows
taskbar_resize.exe -b 220 ===> 6 rows
taskbar_resize.exe -b 250 ===> 7 rows
```
thank you so much for your code and help

if you want me to send a PR I will do it.

if someone needs the compiled version and source here it is [_build.zip](https://github.com/m417z/taskbar-resize/files/12502149/_build.zip)

**Comment by m417z** [comment]
Great, I'm glad that worked.

> if you want me to send a PR I will do it.

Sure, why not. You can also add the info from your comment to the readme.

**Comment by badrelmers** [comment]
done
I uploaded a compiled version for xp+ if you want to add it in your repo
https://github.com/badrelmers/taskbar-resize/releases/tag/v1
